### ISSUE TITLE
Implement a overview in dashboard

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#100]
We need have a global overview of the tables with custom filters.
We need to discuss and agree which approach we will have for this issue.

**Comment by cph-lh** [comment]
Jeg synes det er fedt at man har sin "egen" side, da det kan blive uoverskueligt at skulle filtere bare for at se sin egen tid. Det er ikke alle som er interesseret i at skulle sidde og filterer, hvis de bare gerne vil se hvilke timer de har og om de er blevet betalt osv..

**Comment by astyltsvig** [comment]
Jeg er enige med dig @cph-lh, så vores umiddelbare nav menuer bliver sådan:

1. Dashboard
2. Register work
3. Overview
3.1 My timeregs
3.2 analysis

**Comment by astyltsvig** [comment]
Closed with #111
