### ISSUE TITLE
Further design and implementation

### ISSUE THREAD

**Issue by bentreadwell** [prolike/dilly-dally#109]
Having closed on #57, we decided to let @Ansty93 and @cph-lh focus some more on the backend development of the project. But now, they're at a stage where they need some styling to the functionalities they've implemented so far. 

This issue involves designing a better layout for the initial Google authentication page, the transition there after as well as the Time Registration page. When the design for all of these has been agreed upon, it's time to implement it within the code base itself.

**Comment by cph-lh** [comment]
This issue is too big and have been split into separate issues (#87, #99, #116)

**Comment by astyltsvig** [comment]
We will make a single issue for all new design implementations, therefore the issue is now closed.
