### ISSUE TITLE
Feature - Set up a simple sample frontend

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#12]
The application should just be a plain and simple frontend and interacts with a database.

Follow this tutorial: https://www.youtube.com/watch?v=2Vf1D-rUMwE

**Comment by astyltsvig** [comment]
@cph-lh 
Here a quickstart sample example, maybe something you would rather take a look onto?

https://github.com/firebase/quickstart-js/tree/master/firestore

**Comment by astyltsvig** [comment]
Please review this commit, and see if thats something you could use

**Comment by astyltsvig** [comment]
https://firebase.google.com/docs/firestore/quickstart

**Comment by cph-lh** [comment]
Input is stored, but not correctly. It should make a new document, instead of resetting the values.

**Comment by cph-lh** [comment]
We need to use add() instead of set()
https://stackoverflow.com/questions/47474522/firestore-set-add
https://cloud.google.com/nodejs/docs/reference/firestore/0.20.x/CollectionReference#add
