### ISSUE TITLE
Implement a clock-picker for timereg

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#145]

**Comment by cph-lh** [comment]
We would like to have a timepicker so that it will be easier for mobile users to enter time.
We are going to use Buefy, as we did with the rest of the registration form. https://buefy.org/documentation/timepicker

**Comment by cph-lh** [comment]
Currently having issues with the input type of the Buefy timepicker. By default, it is a Date, but we need it to be a String ("10:00"), as we can't we create our custom Date object with the start/end time as dates.
