### ISSUE TITLE
Timepicker error msg fix

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#158]
When you pick a time, but moves focus to other before you complete the time input, you wll get a error message.

But when you go back and complete the timeinput, the error message will still appear until you save the timeregistration.

It should go away instantly when you enter a correct time.

**Comment by cph-lh** [comment]
Might be irrelevant as we're planning to go away from the time picker and instead use a clock picker with #145.

**Comment by astyltsvig** [comment]
It is resolved
