### ISSUE TITLE
Create DNS records for www.stage.stack.prolike.io

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#164]
## Issue
We would like to have the firebase app to be connected with the domain www.stack.prolike.io

## Discussion
We need to add the txt records into the DNS provider of www.prolike.io for verifying that we own prolike.io

## Additional info
The DNS records should be pointed to our production and stage pages in firebaseapps.

- **Stage**
**Firebase url:** ~www.~prolike-stack.firebaseapp.com
**Prolike domain url:** www.stage.stack.prolike.io

DNS RECORD TXT:

google-site-verification=unilKBah956LMBuqEU9UgvcLkMa3BjRBaRobSlLYcD4

**Comment by lakruzz** [comment]
Done.

 wait for them to be replicated 2-9 hours

Check at https://who.is/dns/prolike.io and

**Comment by lakruzz** [comment]
![image](https://user-images.githubusercontent.com/155492/55238389-b467f680-5234-11e9-8506-89738eb9b0c1.png)

**Comment by astyltsvig** [comment]
Looks like https://stage.stack.prolike.io is up and running.
Therefore the issue is now resolved and closed.
