### ISSUE TITLE
Fix router issues

### ISSUE THREAD

**Issue by cph-lh** [prolike/dilly-dally#172]
## Issue
Right now our routing is messy and if you edit the URL to something invalid you're sent back to the Login page. We need to adjust our routing so that the Dashboard page is the default page if you're logged in and change the URL.

## Discussion
It is not ideal that logged in users are redirected back to the Login page when attempting to navigate through the URL.

## Related to
Emerged from #124

**Comment by astyltsvig** [comment]
Instead of redirecting back to dashboard, we now implement a error 404 page, so when a user enter a errornous URL, he will be showed a 404 page.
