### ISSUE TITLE
Feature - Input fields (Html 5 + bootstrap)

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#20]
A form group with following inputs:
1. Date : (Using a datepicker and it should be automatically set the date as today in start)
2. Project : (Dropdown and can only select one)
3. Hours : Text
4. Category : Dropdown (Dropdown and can only select one)
5. Comment : Text

**Comment by astyltsvig** [comment]
As smaller part of the issue #17

**Comment by bentreadwell** [comment]
https://www.online-convert.com/downloadFile/5ea5f26e-67b2-4a16-9ff5-0c63969d329a/95e8b55d-6e13-4b1b-8c8f-09f1b57a6295
