### ISSUE TITLE
Create production DNS records for www.stack.prolike.io 

### ISSUE THREAD

**Issue by astyltsvig** [prolike/dilly-dally#237]
#Issue
We would like to have the firebase app to be connected with the domain www.stack.prolike.io

#Discussion
We need to add the txt records into the DNS provider of www.prolike.io for verifying that we own prolike.io

#Additional info
The DNS records should be pointed to our production page in firebaseapps.

Production
Firebase url: https://prolike-stack-prod1.firebaseapp.com
Prolike domain url: www.stack.prolike.io

**Comment by astyltsvig** [comment]
*DNS RECORDS INFO* 
```
A | www.stack.prolike.io | 151.101.1.195
A | www.stack.prolike.io | 151.101.65.195

``` 

``` 

A | stack.prolike.io | 151.101.1.195
A | stack.prolike.io  | 151.101.65.195

```

**Comment by astyltsvig** [comment]
Kan du ordne DNS når du får tid @lakruzz

**Comment by lakruzz** [comment]
@Ansty93 Det er de samme som der i øjeblikket peger på stage.stack.prolike.io

Så vores stage miljø bliver til vores prod miljø. ...men hvor er så vores stage miljø?

...Hvorfor er der to ip adresser til den sammen record - har du et link hvor Firebase forklarer de *to* IP adresser?

**Comment by astyltsvig** [comment]
@lakruzz 
Det er sådan som jeg tror: Vi definerer inde i firebase hvilke url peger på denne ip adresse, så der bør være  noget URL redirection/DNS engine som sørger for at brugere lander på den rette firebase domain. 

 - Dokumentation her : [https://firebase.google.com/docs/hosting/custom-domain](url)

**Comment by lakruzz** [comment]
Jeg har oprettet
```
A | stack.prolike.io | 151.101.1.195
A | stack.prolike.io  | 151.101.65.195
`
``

De andre (`www.stack.prolike.io`)  tror jeg ikke vi får brug for
