### ISSUE TITLE
Designing a sweet wireframe

### ISSUE THREAD

**Issue by bentreadwell** [prolike/dilly-dally#57]
Having discussed the visual identity of the site, we're about to make a mock up, containing all the features, wants and desires of the team behind this repository, @Ansty93 and @cph-lh.

The mock ups will be created in [Adobe XD](https://www.adobe.com/dk/products/xd.html), and published here for review by @Ansty93 and @cph-lh, and eventually when they're satisfied with the design, we'll move over to implementing the design into the actual website.

**Comment by astyltsvig** [comment]
Changed the prio to must have

**Comment by bentreadwell** [comment]
Five days later, and we have a working [wireframe](https://xd.adobe.com/view/51b344ce-d615-4176-4da1-d0fdcc32860b-2782/?fullscreen&hints=off)! I couldn't have done it without the help of @Ansty93 and @cph-lh - thanks guys! 😁

**Comment by bentreadwell** [comment]
Designed a new and improved version of the time registration page, allowing for a level of admin overview

https://xd.adobe.com/view/4e5cec3b-af83-413c-4b44-405f69ea1b02-386d/?fullscreen&hints=off
